apiVersion: v1
kind: PersistentVolume
metadata:
  name: vtsweb-pv-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/demo/repositories/vtsdocker/volumes/config
