kind: Service 
apiVersion: v1 
metadata:
  name: vts-service
spec:
  # When the node receives a request 
  # "select pods with the label 'app' set to 'echo-hostname'"
  # and forward the request to one of them
  selector:
    app: vts
  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - port: 4000
      protocol: TCP
      name: admin
    - port: 8888
      protocol: TCP
      name: api

